
name: Executar Script Bash

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Permissões
      run: chmod +x "script1.sh"

    - name: Execute Bash Script
      run: bash script1.sh
      shell: bash

    - name: Run a script
      run: ./script1.sh

    - name: Executar Comandos Linux
      run: |
        # Comando 1
        echo "Executando Comando 1"
        ls -l

        # Comando 2
        echo "Executando Comando 2"
        pwd

        # Comando 3
        echo "Executando Comando 3"
        whoami

        ./script1.sh

        bash script1.sh

        # Comando 3
        echo "Executando Comando 4"

